%YAML 1.2
---
define: &root_path "$HOME/pyssg/pyssg.xyz/"

title: "pyssg"
author: "David Luévano Alvarado"
author_email: "david@luevano.xyz"
description: "PySSG, the python static site generator official website."
lang: "en"
path:
  src: !join [*root_path, "src/pyssg.xyz"]
  dst: !join [*root_path, "live/pyssg.xyz"]
  plt: !join [*root_path, "plt"]
  db: !join [*root_path, "db.psv"]
url:
  main: "https://pyssg.xyz"
  static: "https://static.pyssg.xyz"
  default_image: "images/default.png"
fmt:
  date: "%a, %b %d, %Y @ %H:%M %Z"
  list_date: "%b %d"
  list_sep_date: "%B %Y"
dirs:
  /:
    cfg:
      plt: "root_page.html"
      tags: False
      index: False
      rss: True
      sitemap: True
      exclude_dirs: []
...