%YAML 1.2
---
define: &root "./"

title: "Example site"
path:
  src: !join [*root, "src"]
  dst: !join [*root, "dst"]
  plt: !join [*root, "plt"]
  db: !join [*root, "db"]
url:
  base: "https://example.com"
fmt:
  date: "%a, %b %d, %Y @ %H:%M %Z"
  rss_date: "%a, %d %b %Y %H:%M:%S GMT"
  sitemap_date: "%Y-%m-%d"
info:
  version: "0.0.0"
...
---
dir: "/"
plt: "page.html"
tags: False
tags_prefix: ''
index: False
rss: False
sitemap: False
...
