%YAML 1.2
---
define: &root "./"

title: "Example site"
path:
  src: !join [*root, "src"]
  dst: !join [*root, "dst"]
  plt: !join [*root, "plt"]
  db: !join [*root, "db"]
url:
  base: "https://example.com"
fmt:
  date: "%a, %b %d, %Y @ %H:%M %Z"
  rss_date: "%a, %d %b %Y %H:%M:%S GMT"
  sitemap_date: "%Y-%m-%d"
  list_date: "%b %d"
  list_sep_date: "%Y"
info:
  version: "0.0.0"
...
---
dir: "/"
plt:
  page: "page.html"
  index: "page_index.html"
  tags: "tag_index.html"
  rss: "rss.xml"
  sitemap: "sitemap.xml"
tags_prefix: '@'
...
